In [1]:
from cbp.account.account_mapper import account_data_mapper

In [2]:
# instantiate account_data_mapper class
adm = account_data_mapper()

In [3]:
# Method to get account balances
await adm.get_account_balances()

,id,currency,balance,hold,available,profile_id,trading_enabled
37,c729fb1e-7301-4e7f-9922-8b1e0f5b8853,USD,3381.651188,0.0,3381.651188,f496646e-efbc-4072-baf6-104b182cd36f,1.0
41,3e90cb8c-97e1-4965-8011-1d1708c76b1c,XRP,2034.498567,0.0,2034.498567,f496646e-efbc-4072-baf6-104b182cd36f,1.0
40,6463e8c4-5cd4-46a7-b0dc-dc36a5fc64d2,XLM,2000.000000,0.0,2000.000000,f496646e-efbc-4072-baf6-104b182cd36f,1.0
15,97c4f9ed-132c-4941-92a2-13162fa96ef5,EOS,71.900000,0.0,71.900000,f496646e-efbc-4072-baf6-104b182cd36f,1.0
25,d1abac37-685a-40d8-869c-9aada72a97e7,LTC,22.222778,12.0,10.222778,f496646e-efbc-4072-baf6-104b182cd36f,1.0
17,11d119a5-2a71-4b6f-b54d-708abae22179,ETH,2.003923,0.0,2.003923,f496646e-efbc-4072-baf6-104b182cd36f,1.0

In [4]:
# Method to get PnL of your current positions
await adm.get_all_positions()

,Asset,Balance,Market Price,Market Value,Unit Cost,Cost Basis,Gain/Loss,Pct Gain/Loss
0,XRP,2034.498567,0.249600,507.810842,0.488290,993.424875,-485.614033,-48.882814
1,XLM,2000.000000,0.330964,661.928000,0.001618,3.235743,658.692257,20356.754446
2,EOS,71.900000,3.263000,234.609700,3.455000,248.414500,-13.804800,-5.557164
3,LTC,22.222778,165.960000,3688.092202,89.550000,1990.049751,1698.042451,85.326633
4,ETH,2.003923,1154.740000,2314.010357,37.094707,74.334946,2239.675411,3012.950892
5,Total Portfolio,NaN,NaN,7406.451101,NaN,3309.459815,4096.991286,123.796375

In [31]:
# Method to get account history of particular asset account, e.g. XRP
await adm.get_account_history('ETH')

,id,amount,balance,created_at,type,details
0,3.525575e+09,-2.150000,2.003923,2021-01-03 22:45:25.169126+00:00,match,{'order_id': '91e44376-5de5-4373-aa4d-a9b67d8c...
1,3.097177e+09,0.010096,4.153923,2020-11-26 17:50:25.140277+00:00,match,{'order_id': '937432d8-27ce-4980-9e06-9988fb84...
2,3.096409e+09,1.250000,4.143827,2020-11-26 17:02:52.222159+00:00,match,{'order_id': 'c0b0b188-f53b-4c7c-8e62-4ec4fbb4...
3,3.096385e+09,1.250000,2.893827,2020-11-26 17:02:02.517289+00:00,match,{'order_id': '0cdc9e96-692f-45a6-a56e-a8b0b37d...
4,3.065529e+09,0.321727,1.643827,2020-11-24 20:52:00.018600+00:00,match,{'order_id': 'e1488947-2189-4418-bbcd-66c6bc0c...
5,3.065529e+09,1.322100,1.322100,2020-11-24 20:51:59.943299+00:00,match,{'order_id': 'e1488947-2189-4418-bbcd-66c6bc0c...
6,2.437501e+09,-10.000000,0.000000,2020-08-02 04:41:38.974421+00:00,match,{'order_id': 'fdc3f7ec-fe99-49df-8452-40ea0dfd...
7,2.437177e+09,2.532673,10.000000,2020-08-02 04:38:37.959564+00:00,match,{'order_id': '5659e279-0742-41b9-9358-fe1077dd...
8,2.437177e+09,2.467327,7.467327,2020-08-02 04:38:37.947588+00:00,match,{'order_id': '5659e279-0742-41b9-9358-fe1077dd...
9,2.437148e+09,5.000000,5.000000,2020-08-02 04:38:24.418437+00:00,match,{'order_id': '8dde7dea-d5c4-4076-b1d1-e4cde3b5...
10,2.067987e+09,-0.868473,0.000000,2020-03-28 00:10:49.313413+00:00,match,{'order_id': '50257d11-b596-4c17-ad18-b64e86d7...
11,2.067987e+09,-0.382190,0.868473,2020-03-28 00:10:49.307430+00:00,match,{'order_id': '50257d11-b596-4c17-ad18-b64e86d7...
12,2.067987e+09,-3.749337,1.250663,2020-03-28 00:10:49.300305+00:00,match,{'order_id': '50257d11-b596-4c17-ad18-b64e86d7...
13,2.047789e+09,5.000000,5.000000,2020-03-20 20:30:26.971958+00:00,match,{'order_id': '544ba967-64dd-4f02-a87b-a89279f4...
14,2.034476e+09,-5.000000,0.000000,2020-03-17 21:02:20.191710+00:00,match,{'order_id': '1f55a9c8-5059-4a0b-808a-a98eebeb...
15,2.026823e+09,5.000000,5.000000,2020-03-16 10:02:54.172129+00:00,match,{'order_id': 'c0097377-97e2-4475-bcc5-b76b6a1b...
16,7.495397e+08,-10.000000,0.000000,2018-02-10 06:44:48.994868+00:00,match,{'order_id': 'd2bc88ac-d485-452e-81af-59bd2471...
17,7.178159e+08,0.977843,10.000000,2018-02-02 12:13:55.358642+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
18,7.178112e+08,4.205547,9.022157,2018-02-02 12:13:49.796629+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
19,7.178109e+08,0.585798,4.816609,2018-02-02 12:13:49.436873+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
20,7.178109e+08,2.001490,4.230811,2018-02-02 12:13:49.431917+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
21,7.178109e+08,2.229322,2.229322,2018-02-02 12:13:49.427893+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
22,6.877884e+08,-0.620645,0.000000,2018-01-21 17:36:00.260096+00:00,match,{'order_id': 'bc808fd7-9c01-4ca9-aaa2-19e88c4f...
23,6.877884e+08,-4.379354,0.620645,2018-01-21 17:35:59.895837+00:00,match,{'order_id': 'bc808fd7-9c01-4ca9-aaa2-19e88c4f...
24,6.709715e+08,5.000000,5.000000,2018-01-17 02:43:51.113345+00:00,match,{'order_id': '8363c537-5127-4400-8ae1-f0417eb6...

In [32]:
_.iloc[0]['balance']

2.00392327

In [4]:
# Method to get order history of particular asset trades, e.g. XRP
await adm.get_order_history('XRP')

,created_at,trade_id,product_id,order_id,user_id,profile_id,liquidity,price,size,fee,side,settled,usd_volume
0,2021-01-06 14:07:51.244000+00:00,24490528,XRP-USD,219832f1-7746-43b7-b6ee-624371e0b91d,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,0.23260000,780.35218300,0.9075495888290000,sell,True,181.5099177658000000
1,2021-01-06 14:07:50.878000+00:00,24490527,XRP-USD,219832f1-7746-43b7-b6ee-624371e0b91d,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,0.23260000,219.64781700,0.2554504111710000,sell,True,51.0900822342000000
2,2020-12-29 01:26:24.546000+00:00,23234638,XRP-USD,4af67ba8-8bb2-4338-9b67-4cd1ab87c8fa,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,0.23100000,1000.00000000,1.1550000000000000,buy,True,231.0000000000000000
3,2020-11-26 14:06:34.153000+00:00,16941061,XRP-USD,a5ecd31f-b0d8-4cb0-bbbb-b63c3073ec7c,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,0.51270000,485.18864600,1.2437810940210000,buy,True,248.7562188042000000
4,2020-11-25 03:01:01.295000+00:00,16439650,XRP-USD,6b3280a5-9a0c-4950-a3cd-99078fc4e55a,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,0.64250000,387.16921200,1.2437810935500000,buy,True,248.7562187100000000
5,2020-11-21 21:48:59.058000+00:00,15216312,XRP-USD,ef815610-4cd8-409e-be29-d8cb6fe891c8,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,0.42810000,1162.14070900,2.4875621876145000,buy,True,497.5124375229000000
6,2020-08-02 04:42:04.229000+00:00,11142876,XRP-USD,34158034-45b0-4658-86c2-e8aab740c1ea,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,0.25000000,1800.00000000,1.5750000000000000,sell,True,450.0000000000000000
7,2020-08-02 04:38:35.469000+00:00,11139151,XRP-USD,f60fa79d-ccb9-4441-ba09-9c5347424c56,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,0.30000000,1800.00000000,1.8900000000000000,buy,True,540.0000000000000000

In [7]:
# Method to get current market price of as asset
await adm.get_market_price('BTC')

22556.7

In [9]:
import numpy as np

In [10]:
product = 'ETH'
hist = await adm.get_account_history(product)
if hist is not None:
    idx = hist.index[hist.balance.astype(np.float) == 0].tolist()
    fills = await adm.get_order_history(product)
    if len(idx) == 0:
        lfills = fills
    else:
        last_zero_bal_time = hist.loc[idx[0], 'created_at']
        lfills = fills[fills.created_at > last_zero_bal_time]

In [11]:
lfills

,created_at,trade_id,product_id,order_id,user_id,profile_id,liquidity,price,size,fee,side,settled,usd_volume
0,2021-01-03 22:45:24.478000+00:00,72645694,ETH-USD,91e44376-5de5-4373-aa4d-a9b67d8c7bce,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,1000.00000000,2.15000000,10.7500000000000000,sell,True,2150.0000000000000000
1,2020-11-26 17:50:25.134000+00:00,68223631,ETH-USD,937432d8-27ce-4980-9e06-9988fb8449f3,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,493.75000000,0.01009635,0.0249253640625000,buy,True,4.9850728125000000
2,2020-11-26 17:02:52.215000+00:00,68215845,ETH-USD,c0b0b188-f53b-4c7c-8e62-4ec4fbb4a2cd,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,489.04000000,1.25000000,3.0565000000000000,buy,True,611.3000000000000000
3,2020-11-26 17:02:02.485000+00:00,68215469,ETH-USD,0cdc9e96-692f-45a6-a56e-a8b0b37d8075,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,490.42000000,1.25000000,3.0651250000000000,buy,True,613.0250000000000000
4,2020-11-24 20:51:59.936000+00:00,67943664,ETH-USD,e1488947-2189-4418-bbcd-66c6bc0c68d9,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,605.31000000,0.32172692,0.9737226097260000,buy,True,194.7445219452000000
5,2020-11-24 20:51:59.936000+00:00,67943663,ETH-USD,e1488947-2189-4418-bbcd-66c6bc0c68d9,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,605.31000000,1.32210000,4.0014017550000000,buy,True,800.2803510000000000

In [12]:
hist

,id,amount,balance,created_at,type,details
0,3.525575e+09,-2.150000,2.003923,2021-01-03 22:45:25.169126+00:00,match,{'order_id': '91e44376-5de5-4373-aa4d-a9b67d8c...
1,3.097177e+09,0.010096,4.153923,2020-11-26 17:50:25.140277+00:00,match,{'order_id': '937432d8-27ce-4980-9e06-9988fb84...
2,3.096409e+09,1.250000,4.143827,2020-11-26 17:02:52.222159+00:00,match,{'order_id': 'c0b0b188-f53b-4c7c-8e62-4ec4fbb4...
3,3.096385e+09,1.250000,2.893827,2020-11-26 17:02:02.517289+00:00,match,{'order_id': '0cdc9e96-692f-45a6-a56e-a8b0b37d...
4,3.065529e+09,0.321727,1.643827,2020-11-24 20:52:00.018600+00:00,match,{'order_id': 'e1488947-2189-4418-bbcd-66c6bc0c...
5,3.065529e+09,1.322100,1.322100,2020-11-24 20:51:59.943299+00:00,match,{'order_id': 'e1488947-2189-4418-bbcd-66c6bc0c...
6,2.437501e+09,-10.000000,0.000000,2020-08-02 04:41:38.974421+00:00,match,{'order_id': 'fdc3f7ec-fe99-49df-8452-40ea0dfd...
7,2.437177e+09,2.532673,10.000000,2020-08-02 04:38:37.959564+00:00,match,{'order_id': '5659e279-0742-41b9-9358-fe1077dd...
8,2.437177e+09,2.467327,7.467327,2020-08-02 04:38:37.947588+00:00,match,{'order_id': '5659e279-0742-41b9-9358-fe1077dd...
9,2.437148e+09,5.000000,5.000000,2020-08-02 04:38:24.418437+00:00,match,{'order_id': '8dde7dea-d5c4-4076-b1d1-e4cde3b5...
10,2.067987e+09,-0.868473,0.000000,2020-03-28 00:10:49.313413+00:00,match,{'order_id': '50257d11-b596-4c17-ad18-b64e86d7...
11,2.067987e+09,-0.382190,0.868473,2020-03-28 00:10:49.307430+00:00,match,{'order_id': '50257d11-b596-4c17-ad18-b64e86d7...
12,2.067987e+09,-3.749337,1.250663,2020-03-28 00:10:49.300305+00:00,match,{'order_id': '50257d11-b596-4c17-ad18-b64e86d7...
13,2.047789e+09,5.000000,5.000000,2020-03-20 20:30:26.971958+00:00,match,{'order_id': '544ba967-64dd-4f02-a87b-a89279f4...
14,2.034476e+09,-5.000000,0.000000,2020-03-17 21:02:20.191710+00:00,match,{'order_id': '1f55a9c8-5059-4a0b-808a-a98eebeb...
15,2.026823e+09,5.000000,5.000000,2020-03-16 10:02:54.172129+00:00,match,{'order_id': 'c0097377-97e2-4475-bcc5-b76b6a1b...
16,7.495397e+08,-10.000000,0.000000,2018-02-10 06:44:48.994868+00:00,match,{'order_id': 'd2bc88ac-d485-452e-81af-59bd2471...
17,7.178159e+08,0.977843,10.000000,2018-02-02 12:13:55.358642+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
18,7.178112e+08,4.205547,9.022157,2018-02-02 12:13:49.796629+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
19,7.178109e+08,0.585798,4.816609,2018-02-02 12:13:49.436873+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
20,7.178109e+08,2.001490,4.230811,2018-02-02 12:13:49.431917+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
21,7.178109e+08,2.229322,2.229322,2018-02-02 12:13:49.427893+00:00,match,{'order_id': '2d0ceffb-c526-4f83-b713-b93f9fd8...
22,6.877884e+08,-0.620645,0.000000,2018-01-21 17:36:00.260096+00:00,match,{'order_id': 'bc808fd7-9c01-4ca9-aaa2-19e88c4f...
23,6.877884e+08,-4.379354,0.620645,2018-01-21 17:35:59.895837+00:00,match,{'order_id': 'bc808fd7-9c01-4ca9-aaa2-19e88c4f...
24,6.709715e+08,5.000000,5.000000,2018-01-17 02:43:51.113345+00:00,match,{'order_id': '8363c537-5127-4400-8ae1-f0417eb6...

In [13]:
lfills.sort_values(by='created_at')

,created_at,trade_id,product_id,order_id,user_id,profile_id,liquidity,price,size,fee,side,settled,usd_volume
4,2020-11-24 20:51:59.936000+00:00,67943664,ETH-USD,e1488947-2189-4418-bbcd-66c6bc0c68d9,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,605.31000000,0.32172692,0.9737226097260000,buy,True,194.7445219452000000
5,2020-11-24 20:51:59.936000+00:00,67943663,ETH-USD,e1488947-2189-4418-bbcd-66c6bc0c68d9,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,605.31000000,1.32210000,4.0014017550000000,buy,True,800.2803510000000000
3,2020-11-26 17:02:02.485000+00:00,68215469,ETH-USD,0cdc9e96-692f-45a6-a56e-a8b0b37d8075,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,490.42000000,1.25000000,3.0651250000000000,buy,True,613.0250000000000000
2,2020-11-26 17:02:52.215000+00:00,68215845,ETH-USD,c0b0b188-f53b-4c7c-8e62-4ec4fbb4a2cd,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,489.04000000,1.25000000,3.0565000000000000,buy,True,611.3000000000000000
1,2020-11-26 17:50:25.134000+00:00,68223631,ETH-USD,937432d8-27ce-4980-9e06-9988fb8449f3,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,493.75000000,0.01009635,0.0249253640625000,buy,True,4.9850728125000000
0,2021-01-03 22:45:24.478000+00:00,72645694,ETH-USD,91e44376-5de5-4373-aa4d-a9b67d8c7bce,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,1000.00000000,2.15000000,10.7500000000000000,sell,True,2150.0000000000000000

In [24]:
df = lfills.copy()
df['side_int'] = np.where(lfills['side'] == 'buy', 1, -1)
df

,created_at,trade_id,product_id,order_id,user_id,profile_id,liquidity,price,size,fee,side,settled,usd_volume,side_int
0,2021-01-03 22:45:24.478000+00:00,72645694,ETH-USD,91e44376-5de5-4373-aa4d-a9b67d8c7bce,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,1000.00000000,2.15000000,10.7500000000000000,sell,True,2150.0000000000000000,-1
1,2020-11-26 17:50:25.134000+00:00,68223631,ETH-USD,937432d8-27ce-4980-9e06-9988fb8449f3,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,493.75000000,0.01009635,0.0249253640625000,buy,True,4.9850728125000000,1
2,2020-11-26 17:02:52.215000+00:00,68215845,ETH-USD,c0b0b188-f53b-4c7c-8e62-4ec4fbb4a2cd,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,489.04000000,1.25000000,3.0565000000000000,buy,True,611.3000000000000000,1
3,2020-11-26 17:02:02.485000+00:00,68215469,ETH-USD,0cdc9e96-692f-45a6-a56e-a8b0b37d8075,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,M,490.42000000,1.25000000,3.0651250000000000,buy,True,613.0250000000000000,1
4,2020-11-24 20:51:59.936000+00:00,67943664,ETH-USD,e1488947-2189-4418-bbcd-66c6bc0c68d9,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,605.31000000,0.32172692,0.9737226097260000,buy,True,194.7445219452000000,1
5,2020-11-24 20:51:59.936000+00:00,67943663,ETH-USD,e1488947-2189-4418-bbcd-66c6bc0c68d9,57ab52fc35514835c8378aa8,f496646e-efbc-4072-baf6-104b182cd36f,T,605.31000000,1.32210000,4.0014017550000000,buy,True,800.2803510000000000,1

In [26]:
fill_arr = np.array(df.sort_values(by='created_at')[['price', 'size', 'fee', 'side_int', 'usd_volume']], dtype=np.float)
fill_arr

array([[ 6.05310000e+02,  3.21726920e-01,  9.73722610e-01,
         1.00000000e+00,  1.94744522e+02],
       [ 6.05310000e+02,  1.32210000e+00,  4.00140175e+00,
         1.00000000e+00,  8.00280351e+02],
       [ 4.90420000e+02,  1.25000000e+00,  3.06512500e+00,
         1.00000000e+00,  6.13025000e+02],
       [ 4.89040000e+02,  1.25000000e+00,  3.05650000e+00,
         1.00000000e+00,  6.11300000e+02],
       [ 4.93750000e+02,  1.00963500e-02,  2.49253641e-02,
         1.00000000e+00,  4.98507281e+00],
       [ 1.00000000e+03,  2.15000000e+00,  1.07500000e+01,
        -1.00000000e+00,  2.15000000e+03]])

In [30]:
rlzd = []
tot_cost = []
holding = []
avg_cost = []
for i, row in enumerate(lfills.sort_values(by='created_at').itertuples()):
    if i == 0:
        if row.side == 'buy':
            avg_cost.append(float(row.price))
            holding.append(float(row.size))
            tot_cost.append(avg_cost[0]*quant[0])
            rlzd.append(0.)
            continue
        else:
            raise ValueError('First fill in history is not a buy! Please check order history.')
    p = float(row.price) if row.side == 'buy' else avg_cost[-1]
    q = float(row.size) if row.side == 'buy' else -1.*float(row.size)
    net_gain = 0. if row.side == 'buy' else float(row.size)*(float(row.price) - avg_cost[-1])
    new_tot_cost = tot_cost[-1] + p*q
    new_holding = holding[-1] + q
    new_avg_cost = new_tot_cost/new_holding
    rlzd.append(net_gain)
    tot_cost.append(new_tot_cost)
    holding.append(new_holding)
    avg_cost.append(new_avg_cost)

0
605.31000000
1
605.31000000
2
490.42000000
3
489.04000000
4
493.75000000
5
1000.00000000