In [1]:
from cbp.account.account_mapper import account_data_mapper

In [2]:
# instantiate account_data_mapper class
adm = account_data_mapper()

In [3]:
# Method to get account balances
await adm.get_account_balances()

                                      id currency  ...                            profile_id  trading_enabled
39  6463e8c4-5cd4-46a7-b0dc-dc36a5fc64d2      XLM  ...  f496646e-efbc-4072-baf6-104b182cd36f              1.0
40  3e90cb8c-97e1-4965-8011-1d1708c76b1c      XRP  ...  f496646e-efbc-4072-baf6-104b182cd36f              1.0
15  97c4f9ed-132c-4941-92a2-13162fa96ef5      EOS  ...  f496646e-efbc-4072-baf6-104b182cd36f              1.0
24  d1abac37-685a-40d8-869c-9aada72a97e7      LTC  ...  f496646e-efbc-4072-baf6-104b182cd36f              1.0
17  11d119a5-2a71-4b6f-b54d-708abae22179      ETH  ...  f496646e-efbc-4072-baf6-104b182cd36f              1.0
36  c729fb1e-7301-4e7f-9922-8b1e0f5b8853      USD  ...  f496646e-efbc-4072-baf6-104b182cd36f              1.0

[6 rows x 7 columns]

In [4]:
# Method to get PnL of your current positions
await adm.get_all_positions()

             Asset  Balance Market Price  Market Value Unit Cost   Cost Basis   Gain/Loss  Pct Gain/Loss
0              XLM     4221     0.180473    761.776533  0.176756   746.086950   15.689583       2.102916
1              XRP   2034.5       0.5549   1128.943255  0.489076   995.024875  133.918380      13.458797
2              EOS     71.9        2.998    215.556200     3.455   248.414500  -32.858300     -13.227207
3              LTC  22.2228       100.25   2227.833473     89.55  1990.049751  237.783722      11.948632
4              ETH  4.15392       633.48   2631.427313   535.478  2224.334946  407.092367      18.301757
5  Total Portfolio                         6965.536774            6203.911022  761.625752      12.276542

In [5]:
# Method to get account history of particular asset account, e.g. XRP
await adm.get_account_history('XRP')

             id       amount  ...   type                                            details
0  3.094644e+09   485.188646  ...  match  {'order_id': 'a5ecd31f-b0d8-4cb0-bbbb-b63c3073...
1  3.069560e+09   387.169212  ...  match  {'order_id': '6b3280a5-9a0c-4950-a3cd-99078fc4...
2  3.021272e+09  1162.140709  ...  match  {'order_id': 'ef815610-4cd8-409e-be29-d8cb6fe8...
3  2.437544e+09 -1800.000000  ...  match  {'order_id': '34158034-45b0-4658-86c2-e8aab740...
4  2.437169e+09  1800.000000  ...  match  {'order_id': 'f60fa79d-ccb9-4441-ba09-9c534742...

[5 rows x 6 columns]

In [6]:
# Method to get order history of particular asset trades, e.g. XRP
await adm.get_order_history('XRP')

                        created_at  trade_id product_id  ...  side settled            usd_volume
0 2020-11-26 14:06:34.153000+00:00  16941061    XRP-USD  ...   buy    True  248.7562188042000000
1 2020-11-25 03:01:01.295000+00:00  16439650    XRP-USD  ...   buy    True  248.7562187100000000
2 2020-11-21 21:48:59.058000+00:00  15216312    XRP-USD  ...   buy    True  497.5124375229000000
3 2020-08-02 04:42:04.229000+00:00  11142876    XRP-USD  ...  sell    True  450.0000000000000000
4 2020-08-02 04:38:35.469000+00:00  11139151    XRP-USD  ...   buy    True  540.0000000000000000

[5 rows x 13 columns]

In [7]:
# Method to get current market price of as asset
await adm.get_market_price('BTC')

22556.7